# Generated by Django 4.1.5 on 2023-01-13 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bday',
            field=models.DateField(default=datetime.date(2020, 6, 14)),
        ),
    ]
