# Generated by Django 4.1.5 on 2023-01-13 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_bday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='bday',
            new_name='joinDate',
        ),
    ]
