# Generated by Django 4.1.5 on 2023-01-13 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_rename_bday_employee_joindate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='joinDate',
            field=models.DateField(default=datetime.date(2023, 1, 13)),
        ),
    ]
