# Generated by Django 4.1.5 on 2023-01-15 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_joindate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='joinDate',
            field=models.DateField(default=datetime.datetime(2023, 1, 15, 14, 9, 52, 726652, tzinfo=datetime.timezone.utc)),
        ),
    ]
