# Generated by Django 4.1.5 on 2023-01-16 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_blogpost_alter_employee_joindate'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joinDate',
            field=models.DateField(default=datetime.datetime(2023, 1, 16, 10, 54, 14, 577925, tzinfo=datetime.timezone.utc)),
        ),
    ]
